name:                Covid-Analysis
version:             0.1.0.0
github:              "robert-solomon12/Covid-Analysis"
license:             BSD3
author:              "Robert Solomon"
maintainer:          "20079462@mail.wit.ie"
copyright:           "2021 Robert Solomon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/robert-solomon12/Covid-Analysis#readme>

dependencies:
- base >= 4.7 && < 5
- time >=1.8 && <1.12
- text >=1.2 && <1.3
- csv

library:
  source-dirs: src
exposed-modules: 
    - CleanData
    - CovidData
    - StatsReport
dependencies:
  - split
  - time
  - unique
executables:
  Covid-Analysis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Covid-Analysis

tests:
  Covid-Analysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Covid-Analysis
