name:                Covid-Data-Analysis
version:             0.1.0.0
github:              "githubuser/Covid-Data-Analysis"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Covid-Data-Analysis#readme>

dependencies:
- base >= 4.7 && < 5
- time >=1.8 && <1.12
- text >=1.2 && <1.3
- csv
- sort
- time
- split
- unique


library:
    source-dirs: src
    exposed-modules: 
    - CleanData
    - CovidData
    - StatsReport
  
executables:
  Covid-Data-Analysis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Covid-Data-Analysis

tests:
  Covid-Data-Analysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Covid-Data-Analysis
